# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            The 7th Heaven
#tagline:          'yuhang'
#description:      '7th heaven'
url:              http://y26jin.github.io

author:
  name:           'Shikisama'
  url:            http://my.hupu.com/17675504

paginate:         5

# Version
version:		1.0.0
