# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Hupu User Analysis
#tagline:          'hupuuser'
#description:      'Hupu User Analysis'
url:              http://y26jin.github.io

author:
  name:           'Shikisama'
  url:            http://my.hupu.com/17675504

paginate:         5

# Version
version:		1.0.0
